version: '3.4'
#Para realizar o debug use   
services:
  yowsup:
    image: yowsup
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["python", "/tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 {file}"]
    ports:
      - 5678:5678