version: '3.4'
#Para realizar o debug use python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 {file} 
services:
  yowsup:
    image: yowsup
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp "]
    ports:
      - 5678:5678